
model:
  name: unet_small
  in_channels: 3
  out_channels: 3
  features: [32, 64, 128, 256]

training:
  epochs: 100
  batch_size: 16
  learning_rate: 0.001
  optimizer: adam
  scheduler: cosine

data:
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  augmentation: true
  
augmentation:
  rotation: 15
  scale: 0.1
  brightness: 0.2
  contrast: 0.2
