
version: '3.8'

services:
  ecg2signal:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./outputs:/app/outputs
    environment:
      - ENV=production
      - API_HOST=0.0.0.0
      - API_PORT=8000
